import Foundation

// MARK: - Seed

/// A captured audio idea from Capture Mode
/// Seeds are the fundamental unit of the Seed Library — quick captures of musical moments
public struct Seed: Identifiable, Codable, Sendable {
    public let id: UUID
    public var name: String                    // Auto-generated: "morning_idea_042"
    public var createdAt: Date
    public var duration: TimeInterval          // Duration in seconds
    public var audioFileName: String           // Filename within seed library (e.g., "{uuid}.wav")

    // Auto-detected metadata
    public var detectedBPM: Double?
    public var detectedKey: String?            // e.g., "C major", "D minor"
    public var waveformSamples: [Float]?       // Pre-computed waveform for preview (128-256 samples)

    // User metadata
    public var isStarred: Bool
    public var tags: [String]
    public var rating: Int                     // 0-5 stars
    public var notes: String                   // User notes

    // Capture context
    public var captureSource: CaptureSource    // Where this was captured from
    public var captureDurationRequested: TimeInterval  // How much the user requested (30s, 60s, 120s)
    public var sessionName: String?            // Name of the session when captured

    public init(
        id: UUID = UUID(),
        name: String = "",
        createdAt: Date = Date(),
        duration: TimeInterval = 0,
        audioFileName: String = "",
        detectedBPM: Double? = nil,
        detectedKey: String? = nil,
        waveformSamples: [Float]? = nil,
        isStarred: Bool = false,
        tags: [String] = [],
        rating: Int = 0,
        notes: String = "",
        captureSource: CaptureSource = .rollingBuffer,
        captureDurationRequested: TimeInterval = 30,
        sessionName: String? = nil
    ) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.duration = duration
        self.audioFileName = audioFileName
        self.detectedBPM = detectedBPM
        self.detectedKey = detectedKey
        self.waveformSamples = waveformSamples
        self.isStarred = isStarred
        self.tags = tags
        self.rating = rating
        self.notes = notes
        self.captureSource = captureSource
        self.captureDurationRequested = captureDurationRequested
        self.sessionName = sessionName
    }

    /// Generate an auto-name based on date and sequence
    public static func autoName(date: Date = Date(), sequenceNumber: Int) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "HHmm"
        let timeStr = formatter.string(from: date)

        let hourFormatter = DateFormatter()
        hourFormatter.dateFormat = "HH"
        let hour = Int(hourFormatter.string(from: date)) ?? 12

        let period: String
        switch hour {
        case 5..<12: period = "morning"
        case 12..<17: period = "afternoon"
        case 17..<21: period = "evening"
        default: period = "night"
        }

        return "\(period)_\(timeStr)_\(String(format: "%03d", sequenceNumber))"
    }

    /// Formatted duration string
    public var formattedDuration: String {
        let minutes = Int(duration) / 60
        let seconds = Int(duration) % 60
        if minutes > 0 {
            return "\(minutes):\(String(format: "%02d", seconds))"
        } else {
            return "0:\(String(format: "%02d", seconds))"
        }
    }

    /// Formatted BPM string
    public var formattedBPM: String? {
        guard let bpm = detectedBPM else { return nil }
        return "\(Int(round(bpm))) BPM"
    }

    /// Formatted date string
    public var formattedDate: String {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .short
        return formatter.localizedString(for: createdAt, relativeTo: Date())
    }
}

// MARK: - Capture Source

/// Where a seed was captured from
public enum CaptureSource: String, Codable, Sendable {
    case rollingBuffer      // From the always-on capture buffer
    case loopExport         // Exported from Loop Mode
    case performRecording   // Recorded during Perform Mode
    case audioImport        // Imported audio file
    case aiGenerated        // Generated by AI
}

// MARK: - Seed Sort Options

/// How to sort seeds in the library
public enum SeedSortOrder: String, Codable, Sendable {
    case newestFirst
    case oldestFirst
    case nameAZ
    case nameZA
    case longestFirst
    case shortestFirst
    case bpmLowHigh
    case bpmHighLow
    case ratingHighLow
}

// MARK: - Seed Filter

/// Filter criteria for the seed library
public struct SeedFilter: Codable, Sendable {
    public var starredOnly: Bool
    public var minRating: Int
    public var tags: [String]
    public var dateRange: DateInterval?
    public var bpmRange: ClosedRange<Double>?
    public var keyFilter: String?
    public var searchText: String

    public init(
        starredOnly: Bool = false,
        minRating: Int = 0,
        tags: [String] = [],
        dateRange: DateInterval? = nil,
        bpmRange: ClosedRange<Double>? = nil,
        keyFilter: String? = nil,
        searchText: String = ""
    ) {
        self.starredOnly = starredOnly
        self.minRating = minRating
        self.tags = tags
        self.dateRange = dateRange
        self.bpmRange = bpmRange
        self.keyFilter = keyFilter
        self.searchText = searchText
    }

    /// Whether any filters are active
    public var isActive: Bool {
        starredOnly || minRating > 0 || !tags.isEmpty || dateRange != nil || bpmRange != nil || keyFilter != nil || !searchText.isEmpty
    }

    /// Apply filter to a seed
    public func matches(_ seed: Seed) -> Bool {
        if starredOnly && !seed.isStarred { return false }
        if seed.rating < minRating { return false }
        if !tags.isEmpty && !tags.allSatisfy({ seed.tags.contains($0) }) { return false }
        if let range = dateRange, !range.contains(seed.createdAt) { return false }
        if let bpmRange = bpmRange, let bpm = seed.detectedBPM {
            if !bpmRange.contains(bpm) { return false }
        }
        if let key = keyFilter, seed.detectedKey != key { return false }
        if !searchText.isEmpty {
            let lowered = searchText.lowercased()
            if !seed.name.lowercased().contains(lowered) &&
               !seed.tags.contains(where: { $0.lowercased().contains(lowered) }) &&
               !seed.notes.lowercased().contains(lowered) {
                return false
            }
        }
        return true
    }
}
